### ISSUE TITLE
Python3 commands not running - inconclusive debugging

### ISSUE THREAD

**Issue by sweetvanloan** [Johnathanblackburncodes/prayforsunrise#8]
We are trying to determine what is the cause of the initial issue: python3 manage.py makemigrations, python3 manage.py migrate, and python3 manage.py runserver are all not running at all nor giving errors.

Attempted:
1.  reboot of VS code 
2. python3 manage.py runserver 8000 - which brings forth a syntax error other 2 team members who pulled from the same code does not have.
3. netstat -a, to see if port 8000 is active. It is not.
4. re-committing to git
5. re-pulling from upstream master
6. restarting terminal
7. specifying to terminal to run BASH

**Comment by sweetvanloan** [comment]
running git status and attempting to find issues there

**Comment by cocodes** [comment]
Fixed Merge issue
